### ISSUE TITLE
v0.1.2 for 1.16.5?

### ISSUE THREAD

**Issue by NinekoTheCat** [TechReborn/Energy#12]
I am having the same issue as [is described in this issue](https://github.com/TechReborn/Energy/issues/8). Except I am on 1.16.5.
build.gradle
```gradle
dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	// Energy API
	modImplementation modApi("teamreborn:energy:${project.energy_api_version}")
	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
	// You may need to force-disable transitiveness on them.
}
```
gradle.properties
```properties
# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=1.16.5
	yarn_mappings=1.16.5+build.10
	loader_version=0.12.1

	#Fabric api
	fabric_version=0.40.6+1.16
	#energy api
	energy_api_version=0.1.2
```

**Comment by Technici4n** [comment]
Out of curiosity, is there a reason you are using 1.16 instead of 1.17?

**Comment by NinekoTheCat** [comment]
> Out of curiosity, is there a reason you are using 1.16 instead of 1.17?

I'm using 1.16.5 as I deem it to be more stable. As in, my friend who I play with a lot can't join any server on 1.17

**Comment by Technici4n** [comment]
In 1.16 I'd recommend you use my library FastTransferLib. It was more or less integrated into TR Energy, but only for 1.17. :P

**Comment by NinekoTheCat** [comment]
> In 1.16 I'd recommend you use my library FastTransferLib. It was more or less integrated into TR Energy, but only for 1.17. :P

Thank you I'm sorry for bothering you.
