### ISSUE TITLE
include modAPI leads to crash

### ISSUE THREAD

**Issue by luaxlab** [TechReborn/Energy#18]
Issue:
The use of
```
include modApi('teamreborn:energy:2.1.0')
```
leads to the game crashing, whereas
```
modCompileOnly "teamreborn:energy:2.1.0"
modRuntimeOnly "teamreborn:energy:2.1.0"
```
works without any problem, and the mod beeing recognized/present.

If any other modRuntimes are added, the following line may change to show any arbitrary modid:
`Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-networking-v0'!`

Crashlog:
[crash-2022-01-19_10.29.15-client.txt](https://github.com/TechReborn/Energy/files/7895804/crash-2022-01-19_10.29.15-client.txt)

Steps to reproduce:
1. Clone the fabric example mod and update to following values
```
fabric_version=0.46.1+1.18
minecraft_version=1.18.1
yarn_mappings=1.18.1+build.1
loader_version=0.12.12
```
2. Add reference to this API according to readme
2. Setup / Build
3. Run the client

**Comment by Technici4n** [comment]
Can you try with the following?
```gradle
    include modApi("teamreborn:energy:2.1.0") {
        exclude(group: "net.fabricmc.fabric-api")
    }
```

**Comment by luaxlab** [comment]
When excluding fabric-api as you suggested it works flawlessly.
