### ISSUE TITLE
getEnergyCapacity is not stack aware in SimpleBatteryItem

### ISSUE THREAD

**Issue by AlphaMode** [TechReborn/Energy#21]
This prevents making gadgets or batteries from having a up-gradable capacity

**Comment by Ayutac** [comment]
... simple battery items are not supposed to be stacked?

**Comment by AlphaMode** [comment]
I said stack aware not stacked

**Comment by CodexAdrian** [comment]
What do you mean they arent supposed to be stacked
![image](https://user-images.githubusercontent.com/83074853/187086276-549886b9-a2ae-4b9e-a169-20a3cc5fc5c6.png)

**Comment by drcrazy** [comment]
This issue is about same item but with different capacity. Like if battery has some upgrades still being same item as other batteries of this kind.

More obvious example is a powered helmet with capacity upgrade.
