### ISSUE TITLE
Creating another type of energy

### ISSUE THREAD

**Issue by MJRamon** [TechReborn/Energy#25]
Is there a way to define another type of energy, not RF, and create several energy types in one project?

**Comment by Technici4n** [comment]
Yes, you can define a new BlockApiLookup with a different ID for your mod.

**Comment by MJRamon** [comment]
Kinda new to coding, could you be so kind and give an example?
Or is 
```
	BlockApiLookup<EnergyStorage, Direction> SIDED =
			BlockApiLookup.get(new Identifier("modname:energy_name"), EnergyStorage.class, Direction.class);
```
is all you need? If so, how do I register several energy types?

**Comment by MJRamon** [comment]
Also, how exactly do I define a new EnergyStorage? Do I just create another interface, that extends EnergyStorage interface class?

**Comment by Technici4n** [comment]
Yes that's how you do it, just make sure to use a different Identifier in each BlockApiLookup for each energy type. Once you have a lookup, you can register to it, or query the EnergyStorage

**Comment by Technici4n** [comment]
This is a quote from complicated stuff concept wise, so maybe try to start with something simpler, and work your way up from there
