### ISSUE TITLE
Custom Cable Type

### ISSUE THREAD

**Issue by ChelovekNeWerea25** [TechReborn/Energy#31]
I'm making an energy mod and ran into a cable problem. I need to create my own cables to transmit energy. Could you tell me how?

![image](https://github.com/TechReborn/Energy/assets/133495573/dbbcb045-46c7-4c3f-9ae5-b7530ddb9671)

**Comment by Technici4n** [comment]
This mod exists to support energy implementations, not to teach people how to write cables. Sorry

**Comment by Thepigcat76** [comment]
Maybe take a look at techreborns code for cables or Technici4ns modern dynamics mod?
