### ISSUE TITLE
Can setStored be avoided?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [TechReborn/Energy#5]
I can't think of a case where external objects setting stored energy is useful, but maybe there is one?

I have a use case where setting the stored energy is slower than it would be to insert or extract directly, and would ideally be able to override that behavior

**Comment by drcrazy** [comment]
It is used during world load. For example: https://github.com/TechReborn/RebornCore/blob/4be803f24979416c5dd3e0dbe81237786328f010/src/main/java/reborncore/common/powerSystem/PowerAcceptorBlockEntity.java#L337

**Comment by vpzomtrrfrt** [comment]
sure, but that's internal to PowerAcceptorBlockEntity so it doesn't mean anything else needs to implement it
