### ISSUE TITLE
EnergyHolder interface getTier should have its name changed

### ISSUE THREAD

**Issue by CodexAdrian** [TechReborn/Energy#7]
While yarn mappings of MC use getMaterial in the tool classes to get their material, official mappings use getTier to do that, causing an error if you try to extend TieredItem (or anything that extends it like SwordItem or PickaxeItem) and try implementing EnergyHolder, which is extremely impractical. simply changing getTier() to getEnergyTier() would solve this problem.

**Comment by modmuss50** [comment]
Please migrate to v2, a beta is on maven
